name: check

on:
  schedule:
    - cron: '05 20 * * *'
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: check
        run: |
          chmod +x .github/workflows/check.sh
          .github/workflows/check.sh
