name: keepalive
on:
  schedule:
    - cron: "18 0 * * *"

jobs:
  cronjob-based-github-action:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
